import re
import os
import pdfplumber

def parse_audit_pdf(file_path):
    """
    Parses a Social Media Audit PDF file generated by the SAPA system.
    Extracts complete metadata (titles, URLs, export time, date) and 75-employee matrix.
    """
    filename = os.path.basename(file_path)
    
    audit_date = ""
    export_time = ""
    ig_title = ""
    fb_title = ""
    ig_url = ""
    fb_url = ""
    total_pegawai = 0
    employees = []
    current_divisi = "LAINNYA"
    platform_mode = "all"
    
    with pdfplumber.open(file_path) as pdf:
        # 1. Parse Metadata from page 0 tables and text
        p0 = pdf.pages[0]
        tables = p0.extract_tables()
        if tables:
            meta_table = tables[0]
            for row in meta_table:
                for idx, cell in enumerate(row):
                    if not cell:
                        continue
                    cell_clean = str(cell).strip()
                    if 'TANGGAL AUDIT:' in cell_clean and idx + 1 < len(row) and row[idx+1]:
                        audit_date = str(row[idx+1]).strip()
                    if 'WAKTU EKSPOR:' in cell_clean and idx + 1 < len(row) and row[idx+1]:
                        export_time = str(row[idx+1]).strip()
                    if 'JUDUL IG POST:' in cell_clean and idx + 1 < len(row) and row[idx+1]:
                        ig_title = str(row[idx+1]).replace('\n', ' ').strip()
                    if 'JUDUL FB POST:' in cell_clean and idx + 1 < len(row) and row[idx+1]:
                        fb_title = str(row[idx+1]).replace('\n', ' ').strip()
                    if 'TOTAL PEGAWAI:' in cell_clean and idx + 1 < len(row) and row[idx+1]:
                        m = re.search(r'(\d+)', str(row[idx+1]))
                        if m:
                            total_pegawai = int(m.group(1))
                    if 'TARGET' in cell_clean and ('URL' in cell_clean or 'POST' in cell_clean) and idx + 1 < len(row) and row[idx+1]:
                        val = str(row[idx+1]).replace('\n', ' ')
                        m_ig = re.search(r'IG:\s*([^\s|]+)', val) or re.search(r'(https?://(?:www\.)?instagram\.com/[^\s|]+)', val)
                        if m_ig:
                            ig_url = m_ig.group(1).strip()
                        m_fb = re.search(r'FB:\s*([^\s|]+)', val) or re.search(r'(https?://(?:www\.)?facebook\.com/[^\s|]+)', val)
                        if m_fb:
                            fb_url = m_fb.group(1).strip()
                    if 'PLATFORM FILTER:' in cell_clean and idx + 1 < len(row) and row[idx+1]:
                        pf = str(row[idx+1]).upper()
                        if 'INSTAGRAM' in pf:
                            platform_mode = 'ig'
                        elif 'FACEBOOK' in pf:
                            platform_mode = 'fb'

        # Fallback metadata from raw text if table missing
        if not audit_date:
            text0 = p0.extract_text() or ""
            m_d = re.search(r'TANGGAL AUDIT:\s*(\d{4}-\d{2}-\d{2})', text0)
            if m_d:
                audit_date = m_d.group(1)
            m_e = re.search(r'WAKTU EKSPOR:\s*(\d{2}-\d{2}-\d{4}\s+\d{2}:\d{2}:\d{2}\s+WIB)', text0)
            if m_e:
                export_time = m_e.group(1)

        # 2. Extract Employee Interaction Rows across all pages
        for page in pdf.pages:
            t_list = page.extract_tables()
            for t in t_list:
                for row in t:
                    if not row or not any(row):
                        continue
                    row_str = ' '.join([str(c) for c in row if c])
                    
                    # Division header row
                    if 'DIVISI:' in row_str:
                        current_divisi = row_str.replace('DIVISI:', '').strip()
                        continue
                    
                    # Check if row is employee data row (starts with integer NO)
                    if row[0] and str(row[0]).strip().isdigit():
                        no = str(row[0]).strip()
                        nama = str(row[1]).replace('\n', ' ').strip() if len(row) > 1 and row[1] else ''
                        jabatan = str(row[2]).replace('\n', ' ').strip() if len(row) > 2 and row[2] else ''
                        
                        cols_len = len(row)
                        if cols_len == 7:
                            # 7-Column Layout: No, Nama, Jabatan, IG Like, IG Komen, FB Like, FB Komen
                            ig_like = str(row[3]).strip() if row[3] else '-'
                            ig_komen = str(row[4]).strip() if row[4] else '-'
                            fb_like = str(row[5]).strip() if row[5] else '-'
                            fb_komen = str(row[6]).strip() if row[6] else '-'
                        elif cols_len == 5:
                            # 5-Column Filtered Layout
                            if platform_mode == 'ig':
                                ig_like = str(row[3]).strip() if row[3] else '-'
                                ig_komen = str(row[4]).strip() if row[4] else '-'
                                fb_like = '-'
                                fb_komen = '-'
                            else:
                                ig_like = '-'
                                ig_komen = '-'
                                fb_like = str(row[3]).strip() if row[3] else '-'
                                fb_komen = str(row[4]).strip() if row[4] else '-'
                        else:
                            # Legacy 9-Column Layout or fallback
                            ig_like = str(row[3]).strip() if len(row) > 3 and row[3] else '-'
                            ig_komen = str(row[4]).strip() if len(row) > 4 and row[4] else '-'
                            fb_like = str(row[6]).strip() if len(row) > 6 and row[6] else '-'
                            fb_komen = str(row[7]).strip() if len(row) > 7 and row[7] else '-'
                            
                        # Normalize statuses
                        def norm(v):
                            if not v or v in ['None', 'none', '']:
                                return '-'
                            if 'SUDAH' in v.upper():
                                return 'SUDAH'
                            if 'BELUM' in v.upper():
                                return 'BELUM'
                            return v.strip()

                        employees.append({
                            "no": no,
                            "nama": nama,
                            "jabatan": jabatan,
                            "divisi": current_divisi,
                            "ig_like": norm(ig_like),
                            "ig_komen": norm(ig_komen),
                            "ig_share": "-",
                            "fb_like": norm(fb_like),
                            "fb_komen": norm(fb_komen),
                            "fb_share": "-"
                        })

    # Determine display title
    display_title = ""
    if ig_title and ig_title != '-':
        display_title = ig_title
    elif fb_title and fb_title != '-':
        display_title = fb_title
    else:
        display_title = filename.replace('Rekap_Audit_Medsos_Pegawai_Kanwil_Kepri_', '').replace('Rekap_', '').replace('.pdf', '').strip()

    return {
        "filename": filename,
        "post_title": display_title,
        "ig_title": ig_title or "-",
        "fb_title": fb_title or "-",
        "audit_date": audit_date or "2026-08-18",
        "export_time": export_time or "-",
        "total_pegawai": total_pegawai or len(employees),
        "ig_url": ig_url or "-",
        "fb_url": fb_url or "-",
        "employees": employees
    }
